# Generated by Django 4.2.3 on 2023-07-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_blogpost_id_alter_comment_id_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('password1', models.CharField(max_length=100)),
            ],
        ),
    ]
